function getMessage() {
	var i = Math.floor(messages.length * Math.random());
	let thing = document.getElementById("hi");
	thing.innerHTML = messages[i];
};

const messages = [
	"Check your closet before you sleep tonight.",
	"Youre not supposed to be here.",
	"Open the door, its cold in here.",
	"Your bones need to breathe, take them out.",
	"Help me...",
	"Its cold down here.",
	"...",
	"The bugs, they're in your skin.",
	"Crazy? I was crazy once. They locked me in a room. A rubber room. A rubber room with rats. And rats make me crazy. Crazy?",
	"We've been trying to contact you reguarding your cars extended warranty.",
	"Quack!",
	"Hi!", 
	"My name is Walter Hartwell White. I live at 308 Negra Arroyo Lane Albuquerque New Mexico 87104. This is my confession.",
	"pop pop pop pop pop pop pop",
	"Good Soup.",
	"Me-wow!",
	"Five Nights at FrogLegs.",
	"Gaslighting isn't real, you're crazy.",
	"Dont trust the last message.",
	"I really, really love pancakes.",
	"Do I look dapper?",
	"Stop looking at me!",
	"You're so purdy.",
	"Argggggggggggggggggggggggggggggggggg",
	"Save the honkers (stop breast cancer).",
	"my name is James^.",
	"Coding is confusing ngl.",
	"I hope it is nice looking outside!",
	"Wake up Brian!!!!!!",
	"Own a musket for home defense, since that's what the founding fathers intended. Four ruffians break into my house. 'What the devil?' As I grab my powdered wig and Kentucky rifle. Blow a golf ball sized hole through the first man, he's dead on the spot. Draw my pistol on the second man, miss him entirely because it's smoothbore and nails the neighbors dog. I have to resort to the cannon mounted at the top of the stairs loaded with grape shot, 'Tally ho lads' the grape shot shreds two men in the blast, the sound and extra shrapnel set off car alarms. Fix bayonet and charge the last terrified rapscallion. He Bleeds out waiting on the police to arrive since triangular bayonet wounds are impossible to stitch up. Just as the founding fathers intended.",
  	"Hasta la vista, baby.",
	"I feel the need... the need for speed!",
	"May the Force be with you.",
	"There's no place like home.",
	"I'm the king of the world!",
	"It's Alive!!!!!",
	"My mama always said life was like a box of chocolates. But I'm Diabetic.",
	"I'll be back",
	"You're gonna need a bigger boat.",
	"My precious.",
	"Houston, we have a problem.",
	"A martini. Shaken, not stirred.",
	"I'm yer fawther.",
	"Just keep swimming.",
	"Bonk. James Bonk.",
	"You talkin' to me?",
	"There's no place like 127.0.0.1.",
	"Title: A Critical Analysis of Jett and Nick's Website: The Imperative Need for Massive Improvement Introduction: In an era dominated by digital presence, a company's website serves as a crucial gateway to its brand image, customer engagement, and overall success. Jett and Nick's website, however, falls short of meeting contemporary standards, leaving much to be desired. This essay will delve into the myriad issues plaguing their current online platform and argue for the urgent need for massive improvements to enhance user experience, functionality, and overall effectiveness. User Experience: One of the glaring deficiencies in Jett and Nick's website is the subpar user experience it offers. Navigating through the site is often a cumbersome task, with convoluted menus, slow loading times, and an outdated design that fails to capture the attention of the modern user. A responsive and intuitive interface is crucial to retain visitors and convert them into customers. Without a streamlined and user-friendly design, Jett and Nick risk alienating potential clients and losing valuable business opportunities. Outdated Content and Design: The website's content and design suffer from stagnation, reflecting an outdated approach that is no longer aligned with contemporary web standards. The visuals lack vibrancy, and the overall aesthetic fails to convey the dynamic and innovative nature of the company. Additionally, the content appears static, providing little incentive for visitors to return for updated information or engage with the brand. A fresh and engaging design, coupled with regularly updated content, is paramount to keeping the audience captivated and invested in the company's offerings. Ineffective Communication: Effective communication is the lifeblood of any successful website. Jett and Nick's website, unfortunately, falls short in this regard. The lack of clear and concise messaging hinders the site's ability to convey its value proposition to visitors. Essential information about the company's products, services, and mission is buried beneath layers of unnecessary jargon and verbose descriptions. An improved website should prioritize streamlined communication, ensuring that visitors quickly grasp the core aspects of the business without feeling overwhelmed by unnecessary details. Mobile Responsiveness: In an age where a significant portion of web traffic comes from mobile devices, Jett and Nick's website fails to adapt adequately to varying screen sizes. The importance of mobile responsiveness cannot be overstated, as users expect seamless browsing experiences regardless of the device they use. A website that is not optimized for mobile use risks losing a substantial portion of its potential audience. To remain competitive, Jett and Nick must invest in a responsive design that guarantees an optimal viewing experience across a spectrum of devices. Inadequate E-commerce Functionality: For companies engaged in online commerce, an efficient and reliable e-commerce platform is indispensable. Jett and Nick's website, however, exhibits shortcomings in its e-commerce functionality. Issues such as complicated checkout processes, limited payment options, and unreliable transaction security can erode customer trust and impede sales. Improving the e-commerce infrastructure is not only crucial for customer satisfaction but also for maximizing revenue potential in the digital marketplace. Conclusion: Jett and Nick's website is in dire need of massive improvement to remain competitive in an increasingly digital landscape. Addressing issues related to user experience, outdated content and design, ineffective communication, mobile responsiveness, and e-commerce functionality is paramount. By undertaking a comprehensive overhaul of their online platform, Jett and Nick can not only rectify the current shortcomings but also position themselves as a forward-thinking and customer-centric company ready to thrive in the digital age. Failure to make these improvements may result in missed opportunities, dwindling customer engagement, and a diminishing competitive edge in the market.",
	"Meine Mama! hat mir einfach erlaubt das ich Cola Trinken darf wie cool ist das bitte! Jetzt zock ich Fortnite und trink Cola! YIPEEE!",
	"",
]

