function getMessage() {
	var i = Math.floor(messages.length * Math.random());
	let thing = document.getElementById("hi");
	thing.innerHTML = messages[i];
};

const messages = [
	"I know where you sleep.",
	"I'm in your walls.",
	"I will find you",
	"Check your closet before you sleep tonight.",
	"Youre not supposed to be here.",
	"Open the door, its cold in here.",
	"Its always watching.",
	"Your skin looks uncomfy, peel it off.",
	"Your bones need to breathe, take them out.",
	"Help me...",
	"Its cold down here.",
	"...",
	"I can see you.",
	"The bugs, they're in your skin.",
	"Crazy? I was crazy once. They locked me in a room. A rubber room. A rubber room with rats. And rats make me crazy. Crazy?",
	"You're Gay. <3",
	"We've been trying to contact you reguarding your cars extended warranty.",
	"Quack!",
	"Hi!", 
	"My name is Walter Hartwell White. I live at 308 Negra Arroyo Lane Albuquerque New Mexico 87104. This is my confession.",
	"pop pop pop pop pop pop pop",
	"Good Soup.",
	"Me-wow!",
	"Five Nights at FrogLegs.",
	"Gaslighting isn't real, you're crazy.",
	"Dont trust the last message.",
	"I really, really love pancakes.",
	"Do I look dapper?",
	"Stop looking at me!",
	"You are looking at your new step dad, kid.",
	"You're so purdy.",
	"Argggggggggggggggggggggggggggggggggg",
	"Save the honkers (stop breast cancer).",
	"my name is James^.",
	"Coding is confusing ngl.",
	"I hope it is nice looking outside!",
	"Wake up Brian!!!!!!",
	"Own a musket for home defense, since that's what the founding fathers intended. Four ruffians break into my house. 'What the devil?' As I grab my powdered wig and Kentucky rifle. Blow a golf ball sized hole through the first man, he's dead on the spot. Draw my pistol on the second man, miss him entirely because it's smoothbore and nails the neighbors dog. I have to resort to the cannon mounted at the top of the stairs loaded with grape shot, 'Tally ho lads' the grape shot shreds two men in the blast, the sound and extra shrapnel set off car alarms. Fix bayonet and charge the last terrified rapscallion. He Bleeds out waiting on the police to arrive since triangular bayonet wounds are impossible to stitch up. Just as the founding fathers intended.",
  	"Hasta la vista, baby.",
	"I feel the need... the need for speed!",
	"May the Force be with you.",
	"There's no place like home.",
	"I'm the king of the world!",
	"It's Alive!!!!!",
	"My mama always said life was like a box of chocolates. But I'm Diabetic.",
	"I'll be back",
	"You're gonna need a bigger boat.",
	"My precious.",
	"Houston, we have a problem.",
	"A martini. Shaken, not stirred.",
	"I'm yer fawther.",
	"Magic Mirror on the wall, who is the gayest one of all",
	"Just keep swimming.",
	"Bonk. James Bonk.",
	"You talkin' to me?",
	"",
]

